"""Generated by `make sync-schema`. Do not edit by hand.

Re-exports every generated name, so a mapping can write::

    from schema.salesforce import Product2

"""

from .product_variant import CombinedListing, Count, DeliveryProfile, EditableProperty, GiftCardProductSettings, InventoryItem, InventoryItemMeasurement, InventoryLevel, Metafield, MetafieldDefinition, MoneyV2, Product, ProductCompareAtPriceRange, ProductContextualPricing, ProductPriceRangeV2, ProductVariant, ProductVariantContextualPricing, QuantityRule, ResourceFeedback, RestrictedForResource, SEO, TaxonomyCategory, UnitPriceMeasurement  # noqa: F401

__all__ = [
    "CombinedListing",
    "Count",
    "DeliveryProfile",
    "EditableProperty",
    "GiftCardProductSettings",
    "InventoryItem",
    "InventoryItemMeasurement",
    "InventoryLevel",
    "Metafield",
    "MetafieldDefinition",
    "MoneyV2",
    "Product",
    "ProductCompareAtPriceRange",
    "ProductContextualPricing",
    "ProductPriceRangeV2",
    "ProductVariant",
    "ProductVariantContextualPricing",
    "QuantityRule",
    "ResourceFeedback",
    "RestrictedForResource",
    "SEO",
    "TaxonomyCategory",
    "UnitPriceMeasurement",
]
