"""Generated by `make sync-schema`. Do not edit by hand.

System:       shopify
Root:         ProductVariant
Source:       robin-dev-3.myshopify.com
API version:  2026-07
Fetched:      2026-09-17T03:54:18Z
Types:        23

Regenerate with::

    make sync-schema INTEGRATION=integrations/shopify-product-to-salesforce-product SYSTEM=shopify OBJECT=ProductVariant

Every attribute is a ``Field``, which is a ``str`` carrying the dotted
path it resolves to. Nested types are reached by attribute:
``ProductVariant.<object field>.<field>``.
"""

from otter_schema import Field, Node
from otter_schema.shopify import Arg, Connection

__all__ = [
    "ProductVariant",
    "CombinedListing",
    "Count",
    "DeliveryProfile",
    "EditableProperty",
    "GiftCardProductSettings",
    "InventoryItem",
    "InventoryItemMeasurement",
    "InventoryLevel",
    "Metafield",
    "MetafieldDefinition",
    "MoneyV2",
    "Product",
    "ProductCompareAtPriceRange",
    "ProductContextualPricing",
    "ProductPriceRangeV2",
    "ProductVariantContextualPricing",
    "QuantityRule",
    "ResourceFeedback",
    "RestrictedForResource",
    "SEO",
    "TaxonomyCategory",
    "UnitPriceMeasurement",
]


class _ProductVariant(Node):
    """ProductVariant."""

    availableForSale = Field("availableForSale", object_name="ProductVariant", type="Boolean", required=True)

    @property
    def availablePublicationsCount(self) -> "_Count":
        return _Count(self.at("availablePublicationsCount"))

    barcode = Field("barcode", object_name="ProductVariant", type="String", required=False)
    compareAtPrice = Field("compareAtPrice", object_name="ProductVariant", type="Money", required=False)

    @property
    def contextualPricing(self) -> "_ProductVariantContextualPricing":
        return _ProductVariantContextualPricing(self.at("contextualPricing"))

    createdAt = Field("createdAt", object_name="ProductVariant", type="DateTime", required=True)
    defaultCursor = Field("defaultCursor", object_name="ProductVariant", type="String", required=True)

    @property
    def deliveryProfile(self) -> "_DeliveryProfile":
        return _DeliveryProfile(self.at("deliveryProfile"))

    displayName = Field("displayName", object_name="ProductVariant", type="String", required=True)
    id = Field("id", object_name="ProductVariant", type="ID", required=True)

    @property
    def inventoryItem(self) -> "_InventoryItem":
        return _InventoryItem(self.at("inventoryItem"))

    inventoryPolicy = Field("inventoryPolicy", object_name="ProductVariant", type="ProductVariantInventoryPolicy", required=True)
    inventoryQuantity = Field("inventoryQuantity", object_name="ProductVariant", type="Int", required=False)
    legacyResourceId = Field("legacyResourceId", object_name="ProductVariant", type="UnsignedInt64", required=True)

    @property
    def metafield(self) -> "_Metafield":
        return _Metafield(self.at("metafield"))

    position = Field("position", object_name="ProductVariant", type="Int", required=True)
    price = Field("price", object_name="ProductVariant", type="Money", required=True)

    @property
    def product(self) -> "_Product":
        return _Product(self.at("product"))

    publishedOnPublication = Field("publishedOnPublication", object_name="ProductVariant", type="Boolean", required=True)
    requiresComponents = Field("requiresComponents", object_name="ProductVariant", type="Boolean", required=True)

    @property
    def resourcePublicationsCount(self) -> "_Count":
        return _Count(self.at("resourcePublicationsCount"))

    sellableOnlineQuantity = Field("sellableOnlineQuantity", object_name="ProductVariant", type="Int", required=True)

    @property
    def sellingPlanGroupsCount(self) -> "_Count":
        return _Count(self.at("sellingPlanGroupsCount"))

    showUnitPrice = Field("showUnitPrice", object_name="ProductVariant", type="Boolean", required=True)
    sku = Field("sku", object_name="ProductVariant", type="String", required=False)
    taxable = Field("taxable", object_name="ProductVariant", type="Boolean", required=True)
    title = Field("title", object_name="ProductVariant", type="String", required=True)

    @property
    def unitPrice(self) -> "_MoneyV2":
        return _MoneyV2(self.at("unitPrice"))

    @property
    def unitPriceMeasurement(self) -> "_UnitPriceMeasurement":
        return _UnitPriceMeasurement(self.at("unitPriceMeasurement"))

    updatedAt = Field("updatedAt", object_name="ProductVariant", type="DateTime", required=True)


class _CombinedListing(Node):
    """CombinedListing."""

    @property
    def parentProduct(self) -> "_Product":
        return _Product(self.at("parentProduct"))



class _Count(Node):
    """Count."""

    count = Field("count", object_name="Count", type="Int", required=True)
    precision = Field("precision", object_name="Count", type="CountPrecision", required=True)


class _DeliveryProfile(Node):
    """DeliveryProfile."""

    activeMethodDefinitionsCount = Field("activeMethodDefinitionsCount", object_name="DeliveryProfile", type="Int", required=True)
    coversAllItems = Field("coversAllItems", object_name="DeliveryProfile", type="Boolean", required=True)
    default = Field("default", object_name="DeliveryProfile", type="Boolean", required=True)
    id = Field("id", object_name="DeliveryProfile", type="ID", required=True)
    locationsWithoutRatesCount = Field("locationsWithoutRatesCount", object_name="DeliveryProfile", type="Int", required=True)
    name = Field("name", object_name="DeliveryProfile", type="String", required=True)
    originLocationCount = Field("originLocationCount", object_name="DeliveryProfile", type="Int", required=True)

    @property
    def productVariantsCount(self) -> "_Count":
        return _Count(self.at("productVariantsCount"))

    version = Field("version", object_name="DeliveryProfile", type="Int", required=True)
    zoneCountryCount = Field("zoneCountryCount", object_name="DeliveryProfile", type="Int", required=True)


class _EditableProperty(Node):
    """EditableProperty."""

    locked = Field("locked", object_name="EditableProperty", type="Boolean", required=True)
    reason = Field("reason", object_name="EditableProperty", type="FormattedString", required=False)


class _GiftCardProductSettings(Node):
    """GiftCardProductSettings."""

    crossCurrencyRedeemable = Field("crossCurrencyRedeemable", object_name="GiftCardProductSettings", type="Boolean", required=True)
    issuanceCurrency = Field("issuanceCurrency", object_name="GiftCardProductSettings", type="CurrencyCode", required=False)


class _InventoryItem(Node):
    """InventoryItem."""

    countryCodeOfOrigin = Field("countryCodeOfOrigin", object_name="InventoryItem", type="CountryCode", required=False)
    createdAt = Field("createdAt", object_name="InventoryItem", type="DateTime", required=True)
    duplicateSkuCount = Field("duplicateSkuCount", object_name="InventoryItem", type="Int", required=True)
    harmonizedSystemCode = Field("harmonizedSystemCode", object_name="InventoryItem", type="String", required=False)
    id = Field("id", object_name="InventoryItem", type="ID", required=True)
    inventoryHistoryUrl = Field("inventoryHistoryUrl", object_name="InventoryItem", type="URL", required=False)

    @property
    def inventoryLevel(self) -> "_InventoryLevel":
        return _InventoryLevel(self.at("inventoryLevel"))

    legacyResourceId = Field("legacyResourceId", object_name="InventoryItem", type="UnsignedInt64", required=True)

    @property
    def locationsCount(self) -> "_Count":
        return _Count(self.at("locationsCount"))

    @property
    def measurement(self) -> "_InventoryItemMeasurement":
        return _InventoryItemMeasurement(self.at("measurement"))

    provinceCodeOfOrigin = Field("provinceCodeOfOrigin", object_name="InventoryItem", type="String", required=False)
    requiresShipping = Field("requiresShipping", object_name="InventoryItem", type="Boolean", required=True)
    sku = Field("sku", object_name="InventoryItem", type="String", required=False)
    tracked = Field("tracked", object_name="InventoryItem", type="Boolean", required=True)

    @property
    def trackedEditable(self) -> "_EditableProperty":
        return _EditableProperty(self.at("trackedEditable"))

    @property
    def unitCost(self) -> "_MoneyV2":
        return _MoneyV2(self.at("unitCost"))

    updatedAt = Field("updatedAt", object_name="InventoryItem", type="DateTime", required=True)


class _InventoryItemMeasurement(Node):
    """InventoryItemMeasurement."""

    id = Field("id", object_name="InventoryItemMeasurement", type="ID", required=True)

    @property
    def weight(self) -> "_Weight":
        return _Weight(self.at("weight"))



class _InventoryLevel(Node):
    """InventoryLevel."""

    canDeactivate = Field("canDeactivate", object_name="InventoryLevel", type="Boolean", required=True)
    createdAt = Field("createdAt", object_name="InventoryLevel", type="DateTime", required=True)
    deactivationAlert = Field("deactivationAlert", object_name="InventoryLevel", type="String", required=False)
    id = Field("id", object_name="InventoryLevel", type="ID", required=True)
    isActive = Field("isActive", object_name="InventoryLevel", type="Boolean", required=True)

    @property
    def item(self) -> "_InventoryItem":
        return _InventoryItem(self.at("item"))

    @property
    def location(self) -> "_Location":
        return _Location(self.at("location"))

    updatedAt = Field("updatedAt", object_name="InventoryLevel", type="DateTime", required=True)


class _Metafield(Node):
    """Metafield."""

    compareDigest = Field("compareDigest", object_name="Metafield", type="String", required=True)
    createdAt = Field("createdAt", object_name="Metafield", type="DateTime", required=True)

    @property
    def definition(self) -> "_MetafieldDefinition":
        return _MetafieldDefinition(self.at("definition"))

    id = Field("id", object_name="Metafield", type="ID", required=True)
    jsonValue = Field("jsonValue", object_name="Metafield", type="JSON", required=True)
    key = Field("key", object_name="Metafield", type="String", required=True)
    legacyResourceId = Field("legacyResourceId", object_name="Metafield", type="UnsignedInt64", required=True)
    namespace = Field("namespace", object_name="Metafield", type="String", required=True)
    ownerType = Field("ownerType", object_name="Metafield", type="MetafieldOwnerType", required=True)
    sizeInBytes = Field("sizeInBytes", object_name="Metafield", type="Int", required=True)
    type = Field("type", object_name="Metafield", type="String", required=True)
    updatedAt = Field("updatedAt", object_name="Metafield", type="DateTime", required=True)
    value = Field("value", object_name="Metafield", type="String", required=True)


class _MetafieldDefinition(Node):
    """MetafieldDefinition."""

    @property
    def access(self) -> "_MetafieldAccess":
        return _MetafieldAccess(self.at("access"))

    @property
    def capabilities(self) -> "_MetafieldCapabilities":
        return _MetafieldCapabilities(self.at("capabilities"))

    @property
    def constraints(self) -> "_MetafieldDefinitionConstraints":
        return _MetafieldDefinitionConstraints(self.at("constraints"))

    description = Field("description", object_name="MetafieldDefinition", type="String", required=False)
    id = Field("id", object_name="MetafieldDefinition", type="ID", required=True)
    key = Field("key", object_name="MetafieldDefinition", type="String", required=True)
    metafieldsCount = Field("metafieldsCount", object_name="MetafieldDefinition", type="Int", required=True)
    name = Field("name", object_name="MetafieldDefinition", type="String", required=True)
    namespace = Field("namespace", object_name="MetafieldDefinition", type="String", required=True)
    ownerType = Field("ownerType", object_name="MetafieldDefinition", type="MetafieldOwnerType", required=True)
    pinnedPosition = Field("pinnedPosition", object_name="MetafieldDefinition", type="Int", required=False)

    @property
    def standardTemplate(self) -> "_StandardMetafieldDefinitionTemplate":
        return _StandardMetafieldDefinitionTemplate(self.at("standardTemplate"))

    @property
    def type(self) -> "_MetafieldDefinitionType":
        return _MetafieldDefinitionType(self.at("type"))

    useAsCollectionCondition = Field("useAsCollectionCondition", object_name="MetafieldDefinition", type="Boolean", required=True)
    validationStatus = Field("validationStatus", object_name="MetafieldDefinition", type="MetafieldDefinitionValidationStatus", required=True)


class _MoneyV2(Node):
    """MoneyV2."""

    amount = Field("amount", object_name="MoneyV2", type="Decimal", required=True)
    currencyCode = Field("currencyCode", object_name="MoneyV2", type="CurrencyCode", required=True)


class _Product(Node):
    """Product."""

    @property
    def availablePublicationsCount(self) -> "_Count":
        return _Count(self.at("availablePublicationsCount"))

    @property
    def category(self) -> "_TaxonomyCategory":
        return _TaxonomyCategory(self.at("category"))

    @property
    def combinedListing(self) -> "_CombinedListing":
        return _CombinedListing(self.at("combinedListing"))

    combinedListingRole = Field("combinedListingRole", object_name="Product", type="CombinedListingsRole", required=False)

    @property
    def compareAtPriceRange(self) -> "_ProductCompareAtPriceRange":
        return _ProductCompareAtPriceRange(self.at("compareAtPriceRange"))

    @property
    def contextualPricing(self) -> "_ProductContextualPricing":
        return _ProductContextualPricing(self.at("contextualPricing"))

    createdAt = Field("createdAt", object_name="Product", type="DateTime", required=True)
    defaultCursor = Field("defaultCursor", object_name="Product", type="String", required=True)
    description = Field("description", object_name="Product", type="String", required=True)
    descriptionHtml = Field("descriptionHtml", object_name="Product", type="HTML", required=True)

    @property
    def feedback(self) -> "_ResourceFeedback":
        return _ResourceFeedback(self.at("feedback"))

    @property
    def giftCardSettings(self) -> "_GiftCardProductSettings":
        return _GiftCardProductSettings(self.at("giftCardSettings"))

    giftCardTemplateSuffix = Field("giftCardTemplateSuffix", object_name="Product", type="String", required=False)
    handle = Field("handle", object_name="Product", type="String", required=True)
    hasOnlyDefaultVariant = Field("hasOnlyDefaultVariant", object_name="Product", type="Boolean", required=True)
    hasOutOfStockVariants = Field("hasOutOfStockVariants", object_name="Product", type="Boolean", required=True)
    hasVariantsThatRequiresComponents = Field("hasVariantsThatRequiresComponents", object_name="Product", type="Boolean", required=True)
    id = Field("id", object_name="Product", type="ID", required=True)
    inCollection = Field("inCollection", object_name="Product", type="Boolean", required=True)
    isGiftCard = Field("isGiftCard", object_name="Product", type="Boolean", required=True)
    legacyResourceId = Field("legacyResourceId", object_name="Product", type="UnsignedInt64", required=True)

    @property
    def mediaCount(self) -> "_Count":
        return _Count(self.at("mediaCount"))

    @property
    def metafield(self) -> "_Metafield":
        return _Metafield(self.at("metafield"))

    onlineStorePreviewUrl = Field("onlineStorePreviewUrl", object_name="Product", type="URL", required=False)
    onlineStoreUrl = Field("onlineStoreUrl", object_name="Product", type="URL", required=False)

    @property
    def priceRangeV2(self) -> "_ProductPriceRangeV2":
        return _ProductPriceRangeV2(self.at("priceRangeV2"))

    @property
    def productComponentsCount(self) -> "_Count":
        return _Count(self.at("productComponentsCount"))

    productType = Field("productType", object_name="Product", type="String", required=True)
    publishedAt = Field("publishedAt", object_name="Product", type="DateTime", required=False)
    publishedInContext = Field("publishedInContext", object_name="Product", type="Boolean", required=True)
    publishedOnPublication = Field("publishedOnPublication", object_name="Product", type="Boolean", required=True)
    requiresSellingPlan = Field("requiresSellingPlan", object_name="Product", type="Boolean", required=True)

    @property
    def resourcePublicationsCount(self) -> "_Count":
        return _Count(self.at("resourcePublicationsCount"))

    @property
    def restrictedForResource(self) -> "_RestrictedForResource":
        return _RestrictedForResource(self.at("restrictedForResource"))

    @property
    def sellingPlanGroupsCount(self) -> "_Count":
        return _Count(self.at("sellingPlanGroupsCount"))

    @property
    def seo(self) -> "_SEO":
        return _SEO(self.at("seo"))

    status = Field("status", object_name="Product", type="ProductStatus", required=True)
    templateSuffix = Field("templateSuffix", object_name="Product", type="String", required=False)
    title = Field("title", object_name="Product", type="String", required=True)
    totalInventory = Field("totalInventory", object_name="Product", type="Int", required=True)
    tracksInventory = Field("tracksInventory", object_name="Product", type="Boolean", required=True)
    updatedAt = Field("updatedAt", object_name="Product", type="DateTime", required=True)

    @property
    def variantsCount(self) -> "_Count":
        return _Count(self.at("variantsCount"))

    @property
    def variantsInCollectionCount(self) -> "_Count":
        return _Count(self.at("variantsInCollectionCount"))

    vendor = Field("vendor", object_name="Product", type="String", required=True)


class _ProductCompareAtPriceRange(Node):
    """ProductCompareAtPriceRange."""

    @property
    def maxVariantCompareAtPrice(self) -> "_MoneyV2":
        return _MoneyV2(self.at("maxVariantCompareAtPrice"))

    @property
    def minVariantCompareAtPrice(self) -> "_MoneyV2":
        return _MoneyV2(self.at("minVariantCompareAtPrice"))



class _ProductContextualPricing(Node):
    """ProductContextualPricing."""

    fixedQuantityRulesCount = Field("fixedQuantityRulesCount", object_name="ProductContextualPricing", type="Int", required=True)

    @property
    def maxVariantPricing(self) -> "_ProductVariantContextualPricing":
        return _ProductVariantContextualPricing(self.at("maxVariantPricing"))

    @property
    def minVariantPricing(self) -> "_ProductVariantContextualPricing":
        return _ProductVariantContextualPricing(self.at("minVariantPricing"))

    @property
    def priceRange(self) -> "_ProductPriceRangeV2":
        return _ProductPriceRangeV2(self.at("priceRange"))



class _ProductPriceRangeV2(Node):
    """ProductPriceRangeV2."""

    @property
    def maxVariantPrice(self) -> "_MoneyV2":
        return _MoneyV2(self.at("maxVariantPrice"))

    @property
    def minVariantPrice(self) -> "_MoneyV2":
        return _MoneyV2(self.at("minVariantPrice"))



class _ProductVariantContextualPricing(Node):
    """ProductVariantContextualPricing."""

    @property
    def compareAtPrice(self) -> "_MoneyV2":
        return _MoneyV2(self.at("compareAtPrice"))

    @property
    def price(self) -> "_MoneyV2":
        return _MoneyV2(self.at("price"))

    @property
    def quantityRule(self) -> "_QuantityRule":
        return _QuantityRule(self.at("quantityRule"))

    @property
    def unitPrice(self) -> "_MoneyV2":
        return _MoneyV2(self.at("unitPrice"))



class _QuantityRule(Node):
    """QuantityRule."""

    increment = Field("increment", object_name="QuantityRule", type="Int", required=True)
    isDefault = Field("isDefault", object_name="QuantityRule", type="Boolean", required=True)
    maximum = Field("maximum", object_name="QuantityRule", type="Int", required=False)
    minimum = Field("minimum", object_name="QuantityRule", type="Int", required=True)
    originType = Field("originType", object_name="QuantityRule", type="QuantityRuleOriginType", required=True)

    @property
    def productVariant(self) -> "_ProductVariant":
        return _ProductVariant(self.at("productVariant"))



class _ResourceFeedback(Node):
    """ResourceFeedback."""

    summary = Field("summary", object_name="ResourceFeedback", type="String", required=True)


class _RestrictedForResource(Node):
    """RestrictedForResource."""

    restricted = Field("restricted", object_name="RestrictedForResource", type="Boolean", required=True)
    restrictedReason = Field("restrictedReason", object_name="RestrictedForResource", type="String", required=True)


class _SEO(Node):
    """SEO."""

    description = Field("description", object_name="SEO", type="String", required=False)
    title = Field("title", object_name="SEO", type="String", required=False)


class _TaxonomyCategory(Node):
    """TaxonomyCategory."""

    fullName = Field("fullName", object_name="TaxonomyCategory", type="String", required=True)
    id = Field("id", object_name="TaxonomyCategory", type="ID", required=True)
    isArchived = Field("isArchived", object_name="TaxonomyCategory", type="Boolean", required=True)
    isLeaf = Field("isLeaf", object_name="TaxonomyCategory", type="Boolean", required=True)
    isRoot = Field("isRoot", object_name="TaxonomyCategory", type="Boolean", required=True)
    level = Field("level", object_name="TaxonomyCategory", type="Int", required=True)
    name = Field("name", object_name="TaxonomyCategory", type="String", required=True)
    parentId = Field("parentId", object_name="TaxonomyCategory", type="ID", required=False)


class _UnitPriceMeasurement(Node):
    """UnitPriceMeasurement."""

    measuredType = Field("measuredType", object_name="UnitPriceMeasurement", type="UnitPriceMeasurementMeasuredType", required=False)
    quantityUnit = Field("quantityUnit", object_name="UnitPriceMeasurement", type="UnitPriceMeasurementMeasuredUnit", required=False)
    quantityValue = Field("quantityValue", object_name="UnitPriceMeasurement", type="Float", required=True)
    referenceUnit = Field("referenceUnit", object_name="UnitPriceMeasurement", type="UnitPriceMeasurementMeasuredUnit", required=False)
    referenceValue = Field("referenceValue", object_name="UnitPriceMeasurement", type="Int", required=True)


_ProductVariant.ROOT = Connection(
    'productVariants',
    {
        'after': Arg('String'),
        'before': Arg('String'),
        'first': Arg('Int'),
        'last': Arg('Int'),
        'query': Arg('String'),
        'reverse': Arg('Boolean'),
        'savedSearchId': Arg('ID'),
        'sortKey': Arg('ProductVariantSortKeys', values=('FULL_TITLE', 'ID', 'INVENTORY_LEVELS_AVAILABLE', 'INVENTORY_MANAGEMENT', 'INVENTORY_POLICY', 'INVENTORY_QUANTITY', 'NAME', 'POPULAR', 'POSITION', 'RELEVANCE', 'SKU', 'TITLE',)),
    },
)


_DeliveryProfile.ROOT = Connection(
    'deliveryProfiles',
    {
        'after': Arg('String'),
        'before': Arg('String'),
        'first': Arg('Int'),
        'last': Arg('Int'),
        'merchantOwnedOnly': Arg('Boolean'),
        'reverse': Arg('Boolean'),
    },
)


_InventoryItem.ROOT = Connection(
    'inventoryItems',
    {
        'after': Arg('String'),
        'before': Arg('String'),
        'first': Arg('Int'),
        'last': Arg('Int'),
        'query': Arg('String'),
        'reverse': Arg('Boolean'),
    },
)


_MetafieldDefinition.ROOT = Connection(
    'metafieldDefinitions',
    {
        'after': Arg('String'),
        'before': Arg('String'),
        'constraintStatus': Arg('MetafieldDefinitionConstraintStatus', values=('CONSTRAINED_AND_UNCONSTRAINED', 'CONSTRAINED_ONLY', 'UNCONSTRAINED_ONLY',)),
        'constraintSubtype': Arg('MetafieldDefinitionConstraintSubtypeIdentifier'),
        'first': Arg('Int'),
        'key': Arg('String'),
        'last': Arg('Int'),
        'namespace': Arg('String'),
        'ownerType': Arg('MetafieldOwnerType', required=True, values=('API_PERMISSION', 'COMPANY', 'COMPANY_LOCATION', 'PAYMENT_CUSTOMIZATION', 'VALIDATION', 'CUSTOMER', 'DELIVERY_CUSTOMIZATION', 'DRAFTORDER', 'GIFT_CARD_TRANSACTION', 'TRANSFER', 'MARKET', 'CARTTRANSFORM', 'COLLECTION', 'PRODUCT', 'PRODUCTVARIANT', 'SELLING_PLAN', 'ARTICLE', 'BLOG', 'PAGE', 'FULFILLMENT_CONSTRAINT_RULE', 'ORDER_ROUTING_LOCATION_RULE', 'DISCOUNT', 'ORDER', 'LOCATION', 'SHOP',)),
        'pinnedStatus': Arg('MetafieldDefinitionPinnedStatus', values=('ANY', 'PINNED', 'UNPINNED',)),
        'query': Arg('String'),
        'reverse': Arg('Boolean'),
        'sortKey': Arg('MetafieldDefinitionSortKeys', values=('ID', 'NAME', 'PINNED_POSITION', 'RELEVANCE',)),
    },
)


_Product.ROOT = Connection(
    'products',
    {
        'after': Arg('String'),
        'before': Arg('String'),
        'first': Arg('Int'),
        'last': Arg('Int'),
        'query': Arg('String'),
        'reverse': Arg('Boolean'),
        'savedSearchId': Arg('ID'),
        'sortKey': Arg('ProductSortKeys', values=('CREATED_AT', 'ID', 'INVENTORY_TOTAL', 'PRODUCT_TYPE', 'PUBLISHED_AT', 'RELEVANCE', 'TITLE', 'UPDATED_AT', 'VENDOR',)),
    },
)

ProductVariant = _ProductVariant()
CombinedListing = _CombinedListing()
Count = _Count()
DeliveryProfile = _DeliveryProfile()
EditableProperty = _EditableProperty()
GiftCardProductSettings = _GiftCardProductSettings()
InventoryItem = _InventoryItem()
InventoryItemMeasurement = _InventoryItemMeasurement()
InventoryLevel = _InventoryLevel()
Metafield = _Metafield()
MetafieldDefinition = _MetafieldDefinition()
MoneyV2 = _MoneyV2()
Product = _Product()
ProductCompareAtPriceRange = _ProductCompareAtPriceRange()
ProductContextualPricing = _ProductContextualPricing()
ProductPriceRangeV2 = _ProductPriceRangeV2()
ProductVariantContextualPricing = _ProductVariantContextualPricing()
QuantityRule = _QuantityRule()
ResourceFeedback = _ResourceFeedback()
RestrictedForResource = _RestrictedForResource()
SEO = _SEO()
TaxonomyCategory = _TaxonomyCategory()
UnitPriceMeasurement = _UnitPriceMeasurement()
