"""Generated by `otter schema pull`. Do not edit by hand.

Re-exports one class per object so a mapping can write::

    from schema.salesforce import Product2

"""

from .product2 import Product2

__all__ = [
    "Product2",
]
