"""Render a Salesforce describe response as a Python schema module.

Pure: it takes the parsed JSON Salesforce returned and produces source text. No
network, no filesystem, no credentials, which is what makes the output testable
against a fixture instead of against an org.

The generated module is meant to be committed and read. Two properties matter
more than brevity:

* **Static symbols.** The field names are real class attributes, not strings
  looked up in a dict at runtime, so an editor can autocomplete them and a typo
  is an ``AttributeError`` at import rather than a rejected record at 3am.
* **Stable output.** Fields and keyword arguments are emitted in a fixed order,
  so regenerating an unchanged schema produces a byte-identical file and the
  diff shows only what actually changed.
"""

import keyword

__all__ = ["attribute_name", "module_name", "render_init", "render_module"]

#: Keyword arguments in emission order, so the same field always renders the
#: same way. ``type`` is always emitted; the rest only when they differ from
#: their default, which keeps the common field to one short line.
_KWARGS = (
    "type",
    "length",
    "external_id",
    "unique",
    "required",
    "read_only",
    "reference_to",
    "picklist",
)

#: Wrap a call once it passes this, so a generated file stays readable.
_WRAP_AT = 100


def module_name(object_name):
    """The module file name for one sObject."""
    return object_name.lower()


def attribute_name(field_name):
    """A Python identifier for a Salesforce API name.

    API names are ``[A-Za-z][A-Za-z0-9_]*`` in practice, so this changes
    nothing almost always. It exists for the exceptions -- a field whose API
    name is a Python keyword -- and because generated code that crashes on
    import is worse than generated code with one odd attribute name.
    """
    name = "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in field_name)
    if not name or name[0].isdigit():
        name = "_" + name
    if keyword.iskeyword(name):
        name += "_"
    return name


def _regenerate_hint(system, integration, object_name):
    """The command that reproduces this file, spelled out so it can be pasted.

    It names the integration because `make sync-schema` defaults to one, and a
    hint that regenerates the wrong schema is worse than no hint.
    """
    parts = ["make sync-schema"]
    if integration:
        parts.append("INTEGRATION=%s" % integration)
    parts.append("SYSTEM=%s" % system)
    parts.append("OBJECT=%s" % object_name)
    return " ".join(parts)


def render_module(object_name, describe, *, system, integration, source_url,
                  api_version, fetched_at, include_picklists=False):
    """Render one object's schema as a Python module.

    ``system`` names where the schema came from and is what tells a reader which
    schema directory this belongs to. Nothing else here is system-specific
    except ``_value``, which translates one system's describe payload into
    :class:`Field` arguments.
    """
    lines = [
        '"""Generated by `make sync-schema`. Do not edit by hand.',
        "",
        "System:       %s" % system,
        "Object:       %s" % object_name,
        "Source:       %s" % source_url,
        "API version:  %s" % api_version,
        "Fetched:      %s" % fetched_at,
        "",
        "Regenerate with::",
        "",
        "    %s" % _regenerate_hint(system, integration, object_name),
        "",
        "Every attribute is a ``Field``, which is a ``str``. It drops straight",
        "into a mapping as a key, and carries its type, length and flags so the",
        "mapping can derive truncation limits and assert its upsert key instead",
        "of restating them as literals.",
        '"""',
        "",
        "from otter_schema import Field",
        "",
        '__all__ = ["%s"]' % object_name,
        "",
        "",
        "class %s:" % object_name,
        '    """Fields on %s."""' % object_name,
        "",
    ]

    entries = sorted(describe.get("fields") or [], key=lambda f: f.get("name") or "")
    if not entries:
        lines.append("    pass")
    for entry in entries:
        lines.extend(_render_field(object_name, entry, include_picklists))

    return "\n".join(lines).rstrip("\n") + "\n"


def render_init(modules):
    """Render the package index that re-exports every generated name.

    ``modules`` maps a module stem to the names it exports. Built from whatever
    is on disk, so pulling one object or type never drops another.
    """
    lines = [
        '"""Generated by `make sync-schema`. Do not edit by hand.',
        "",
        "Re-exports every generated name, so a mapping can write::",
        "",
        "    from schema.salesforce import Product2",
        "",
        '"""',
        "",
    ]
    names = []
    for stem in sorted(modules):
        for name in sorted(modules[stem]):
            if name not in names:
                names.append(name)
    for stem in sorted(modules):
        lines.append("from .%s import %s  # noqa: F401"
                     % (stem, ", ".join(sorted(modules[stem]))))
    lines.append("")
    lines.append("__all__ = [")
    for name in sorted(names):
        lines.append('    "%s",' % name)
    lines.append("]")
    return "\n".join(lines).rstrip("\n") + "\n"


def _render_field(object_name, entry, include_picklists):
    name = entry.get("name")
    if not name:
        return []

    kwargs = [("object_name", object_name)]
    for key in _KWARGS:
        value = _value(entry, key, include_picklists)
        if value is None:
            continue
        kwargs.append((key, value))

    attr = attribute_name(name)
    call = _render_call("    %s = " % attr, "Field", ('"%s"' % name,), kwargs)

    rendered = call.split("\n")
    if attr != name:
        # The attribute is renamed; the Field still holds the real API name, so
        # mappings are unaffected.
        rendered[-1] += "  # %s" % name
    return rendered


def _render_call(prefix, func, args, kwargs):
    """One line when it fits, otherwise greedy-packed arguments.

    Packing several arguments per line rather than one keeps the generated file
    scannable: a field with five flags is still five readable lines, not twenty.
    """
    parts = list(args) + ["%s=%s" % (key, _literal(value)) for key, value in kwargs]
    flat = "%s%s(%s)" % (prefix, func, ", ".join(parts))
    if "\n" not in flat and len(flat) <= _WRAP_AT:
        return flat

    indent = "        "
    out = ["%s%s(" % (prefix, func)]
    line = indent
    for part in parts:
        piece = part + ","
        if len(indent) + len(piece) > _WRAP_AT:
            # Too long for any line on its own: a long picklist, say. Give it
            # its own block rather than letting it run off the edge.
            if line.strip():
                out.append(line.rstrip())
                line = indent
            out.extend(piece.split("\n"))
            continue
        if line.strip() and len(line) + len(piece) > _WRAP_AT:
            out.append(line.rstrip())
            line = indent
        line += piece + " "
    if line.strip():
        out.append(line.rstrip())
    out.append("    )")
    return "\n".join(out)


def _value(entry, key, include_picklists):
    if key == "type":
        return entry.get("type") or "string"
    if key == "length":
        return entry.get("length") or None
    if key == "external_id":
        return True if entry.get("externalId") else None
    if key == "unique":
        return True if entry.get("unique") else None
    if key == "required":
        # Required at create: the org insists and will not fill it in itself.
        required = (entry.get("createable") and not entry.get("nillable")
                    and not entry.get("defaultedOnCreate"))
        return True if required else None
    if key == "read_only":
        # The interesting half of createable/updateable, and rare enough to be
        # worth a line when it appears.
        return True if not entry.get("createable") else None
    if key == "reference_to":
        targets = tuple(entry.get("referenceTo") or ())
        return targets or None
    if key == "picklist":
        if not include_picklists:
            return None
        values = tuple(
            str(v.get("value")) for v in (entry.get("picklistValues") or ())
            if v.get("active", True) and v.get("value") is not None
        )
        return values or None
    return None


def _literal(value):
    if value is True:
        return "True"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, tuple):
        if not value:
            return "()"
        flat = "(%s)" % ", ".join('"%s"' % item for item in value)
        if len(flat) <= 60:
            return flat
        # A long picklist: one value per line.
        inner = "\n".join('            "%s",' % item for item in value)
        return "(\n%s\n        )" % inner
    return '"%s"' % value
